# Generated by Django 4.0.5 on 2022-06-23 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactRequest',
            new_name='ContactRequests',
        ),
        migrations.RenameModel(
            old_name='Item',
            new_name='Items',
        ),
        migrations.RenameModel(
            old_name='VolunteeringApplication',
            new_name='VolunteeringApplications',
        ),
        migrations.RenameModel(
            old_name='VolunteeringOpportunity',
            new_name='VolunteeringOpportunities',
        ),
    ]
