# Generated by Django 4.0.5 on 2022-06-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_contactrequest_contactrequests_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.RemoveField(
            model_name='volunteeringapplications',
            name='description',
        ),
        migrations.AlterField(
            model_name='contactrequests',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactrequests',
            name='message',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='contactrequests',
            name='phoneNumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteeringapplications',
            name='phoneNumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteeringopportunities',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='volunteeringopportunities',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
