# Generated by Django 4.0.5 on 2022-06-26 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_items_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactRequests',
            new_name='ContactRequest',
        ),
        migrations.RenameModel(
            old_name='VolunteeringApplications',
            new_name='VolunteeringApplication',
        ),
        migrations.RenameModel(
            old_name='VolunteeringOpportunities',
            new_name='VolunteeringOpportunity',
        ),
    ]
